### ISSUE TITLE
Min/Max Values

### ISSUE THREAD

**Issue by Colorado4Wheeler** [webdeck/homebridge-indigo2#4]
We discussed adding these to the JSON payload so you could dynamically change the lower and upper limits of the characteristic in real-time (versus me editing the HapNode files), I am now passing maxValue and minValue with each characteristic in the next version.

One question I have is that not all characteristics support this, for instance boolean doesn't have it because it's not needed, many of the 0/1 values don't either.  It's mostly for spans of 3 or more possible values.  How does this impact things or how I should pass these to you?

**Comment by webdeck** [comment]
I would recommend only passing this when you want to override the default min and max values.

**Comment by Colorado4Wheeler** [comment]
That will be a little work but that’s what I’ll do.

**Comment by webdeck** [comment]
Just took a look and I see maxValue=0 and minValue=0 for booleans - that would be bad since true is 1.

**Comment by webdeck** [comment]
Actually, everything is showing up with "maxValue": 0, "minValue": 0

**Comment by Colorado4Wheeler** [comment]
Ok, for the 22.2 (or 23, depending on what the next version comes out as) I'll pass a "changeMinMax" boolean state that will indicate if the script should send overriding min/max values.

**Comment by webdeck** [comment]
Adding changeMinMax support.
